### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by lea-33** [NFDI4BIOIMAGE/SlideInsight#13]
Brainstorm about Caching:
- saving pdfs local and only retrieving images from those I have selected (e.g. via the sliceplot viewer)

**Comment by haesleinhuepf** [comment]
Also it would be great if the embedding vectors of slides could be cached. In this way, we only run the (costly) embedding once.

**Comment by lea-33** [comment]
do you have any other ideas on that?
git-bob comment
