### ISSUE TITLE
Providing the .json dict

### ISSUE THREAD

**Issue by lea-33** [NFDI4BIOIMAGE/SlideInsight#14]
Right now the dictionary with the image-text pairs is not available on github, thus the notebook is not working.
Idea: Storing and downloading it with huggingface!

**Comment by haesleinhuepf** [comment]
Hint: I'm uploading a json file to Huggingface in this notebook: https://scads.github.io/generative-ai-notebooks/71_fine_tuning_hf/hf_data_upload.html

**Comment by lea-33** [comment]
@haesleinhuepf Thanks! I now implemented saving the file on huggingface. I also want to do the same for the images, I'll do that next week! But thanks for the notebook, that helped a lot.
